import type {
  DailyCheckIn,
  MoveExercise,
  ProgramPhase,
  UserProfile,
  WorkoutCompletion,
} from "../shared/types";
import type { DayTemplate } from "../sport-data/programs/weekTemplate";

export const testProfile: UserProfile = {
  firstName: "Marie",
  age: 68,
  fitnessLevel: "returning",
  goals: ["energy", "strength", "mobility", "balance"],
  sensitiveAreas: [],
  equipment: ["chair", "mat"],
  onboardingCompleted: true,
};

export const testPhase: ProgramPhase = {
  id: "phase-test",
  name: "Phase de test",
  startWeek: 1,
  endWeek: 12,
  description: "",
  volumeMultiplier: 1,
  difficultyCap: 3,
};

/** A small, controlled exercise catalog covering every rule the engine needs to satisfy. */
export const testExercises: MoveExercise[] = [
  {
    id: "strength-a",
    name: "Force A",
    category: "strength",
    description: "",
    startingPosition: "Position de départ de test.",
    instructions: ["Fais le mouvement."],
    repetitions: 8,
    position: "standing",
    requiredEquipment: [],
    difficulty: 1,
    lowImpact: true,
    avoidWith: ["knees"],
    illustrationKey: "strength-a",
    primaryBenefits: [],
    bodyAreas: ["legs"],
    repeatability: "normal",
  },
  {
    id: "strength-b",
    name: "Force B",
    category: "strength",
    description: "",
    startingPosition: "Position de départ de test.",
    instructions: ["Fais le mouvement."],
    repetitions: 8,
    position: "standing",
    requiredEquipment: [],
    difficulty: 1,
    lowImpact: true,
    illustrationKey: "strength-b",
    primaryBenefits: [],
    bodyAreas: ["arms"],
    repeatability: "normal",
  },
  {
    id: "strength-c",
    name: "Force C",
    category: "strength",
    description: "",
    startingPosition: "Position de départ de test.",
    instructions: ["Fais le mouvement."],
    repetitions: 8,
    position: "standing",
    requiredEquipment: [],
    difficulty: 1,
    lowImpact: true,
    illustrationKey: "strength-c",
    primaryBenefits: [],
    bodyAreas: ["glutes"],
    repeatability: "normal",
  },
  {
    id: "mobility-a",
    name: "Mobilité A",
    category: "mobility",
    description: "",
    startingPosition: "Position de départ de test.",
    instructions: ["Fais le mouvement."],
    repetitions: 8,
    position: "seated",
    requiredEquipment: [],
    difficulty: 1,
    lowImpact: true,
    illustrationKey: "mobility-a",
    primaryBenefits: [],
    bodyAreas: ["shoulders"],
    repeatability: "daily",
  },
  {
    id: "mobility-b",
    name: "Mobilité B",
    category: "mobility",
    description: "",
    startingPosition: "Position de départ de test.",
    instructions: ["Fais le mouvement."],
    durationSeconds: 20,
    position: "seated",
    requiredEquipment: [],
    difficulty: 1,
    lowImpact: true,
    illustrationKey: "mobility-b",
    primaryBenefits: [],
    bodyAreas: ["back"],
    repeatability: "frequent",
  },
  {
    id: "core-sensitive",
    name: "Core sensible",
    category: "pilates",
    description: "",
    startingPosition: "Position de départ de test.",
    instructions: ["Fais le mouvement."],
    repetitions: 6,
    position: "floor",
    requiredEquipment: ["mat"],
    difficulty: 2,
    lowImpact: true,
    illustrationKey: "core-sensitive",
    primaryBenefits: [],
    bodyAreas: ["core"],
    repeatability: "recovery_sensitive",
  },
  {
    id: "balance-a",
    name: "Équilibre A",
    category: "balance",
    description: "",
    startingPosition: "Position de départ de test.",
    instructions: ["Fais le mouvement."],
    durationSeconds: 15,
    position: "supported",
    requiredEquipment: ["chair"],
    difficulty: 1,
    lowImpact: true,
    illustrationKey: "balance-a",
    primaryBenefits: [],
    bodyAreas: ["legs", "core"],
    repeatability: "normal",
  },
  {
    id: "cardio-a",
    name: "Cardio A",
    category: "cardio",
    description: "",
    startingPosition: "Position de départ de test.",
    instructions: ["Fais le mouvement."],
    durationSeconds: 30,
    position: "standing",
    requiredEquipment: [],
    difficulty: 1,
    lowImpact: true,
    illustrationKey: "cardio-a",
    primaryBenefits: [],
    bodyAreas: ["full_body"],
    repeatability: "daily",
  },
];

export const testExercisesById: Record<string, MoveExercise> = Object.fromEntries(
  testExercises.map((e) => [e.id, e]),
);

export const testDayTemplate: DayTemplate = {
  dayNumber: 1,
  title: "Jour de test",
  focus: ["strength", "balance"],
  warmupCategories: ["mobility"],
  warmupCount: 2,
  mainSlots: [
    { category: "strength", count: 2 },
    { category: "balance", count: 1 },
  ],
  cooldownCategories: ["mobility"],
  cooldownCount: 1,
};

export function makeCompletion(overrides: Partial<WorkoutCompletion> = {}): WorkoutCompletion {
  return {
    workoutId: "week-1-day-1",
    completedAt: "2026-01-05T10:00:00.000Z",
    weekNumber: 1,
    dayNumber: 1,
    plannedDurationMinutes: 18,
    difficultyFeedback: "just_right",
    dailyEnergy: "good",
    exerciseIds: ["strength-b"],
    ...overrides,
  };
}

export function makeCheckIn(overrides: Partial<DailyCheckIn> = {}): DailyCheckIn {
  return {
    date: "2026-01-05",
    energy: "good",
    painArea: "none",
    ...overrides,
  };
}
