import type { MoveExercise } from "../../shared/types";

export const balanceExercises: MoveExercise[] = [
  {
    id: "weight-shift",
    name: "Transfert de poids",
    category: "balance",
    description: "La base du travail d'équilibre : déplacer son poids d'un pied à l'autre en confiance.",
    startingPosition: "Debout, pieds à largeur des hanches, mains posées sur le dossier d'une chaise si besoin.",
    instructions: [
      "Transfère doucement ton poids sur le pied droit.",
      "Transfère doucement ton poids sur le pied gauche.",
      "Continue en alternant.",
    ],
    repetitions: 8,
    position: "supported",
    requiredEquipment: ["chair"],
    difficulty: 1,
    lowImpact: true,
    illustrationKey: "weight-shift",
    primaryBenefits: ["Équilibre", "Confiance dans les appuis"],
    cues: ["Garde le regard fixe devant toi", "Mouvement lent et contrôlé"],
    breathingCue: "Respire librement, sans bloquer.",
    bodyAreas: ["legs", "core"],
    repeatability: "frequent",
  },
  {
    id: "assisted-single-leg-balance",
    name: "Équilibre assisté sur un pied",
    category: "balance",
    description: "Travaille l'équilibre unipodal en toute sécurité, avec un appui à disposition.",
    startingPosition: "Debout près d'une chaise, tiens légèrement le dossier d'une main.",
    instructions: [
      "Lève un pied de quelques centimètres du sol.",
      "Maintiens la position.",
      "Repose le pied, puis change de côté.",
    ],
    durationSeconds: 15,
    position: "supported",
    requiredEquipment: ["chair"],
    difficulty: 2,
    lowImpact: true,
    avoidWith: ["ankles"],
    easierVariation: "Garde les orteils du pied levé au contact du sol.",
    harderVariation: "Relâche légèrement l'appui sur la chaise.",
    illustrationKey: "assisted-single-leg-balance",
    primaryBenefits: ["Équilibre", "Stabilité des chevilles"],
    cues: ["Fixe un point devant toi pour t'aider à rester stable", "Garde la chaise à portée de main"],
    breathingCue: "Respire calmement pendant le maintien.",
    bodyAreas: ["legs", "core"],
    repeatability: "normal",
  },
  {
    id: "assisted-heel-to-toe-walk",
    name: "Marche talon-pointe assistée",
    category: "balance",
    description: "Une marche en ligne, talon contre pointe, pour travailler la précision des appuis.",
    startingPosition: "Longe un mur ou un plan de travail pour pouvoir t'appuyer d'une main.",
    instructions: [
      "Avance en posant le talon juste devant les orteils de l'autre pied.",
      "Continue pas à pas, avec contrôle.",
    ],
    repetitions: 8,
    position: "supported",
    requiredEquipment: [],
    difficulty: 2,
    lowImpact: true,
    avoidWith: ["ankles"],
    easierVariation: "Laisse un petit espace entre le talon et la pointe.",
    illustrationKey: "assisted-heel-to-toe-walk",
    primaryBenefits: ["Équilibre", "Précision des appuis"],
    cues: ["Garde une main proche du mur ou du plan de travail", "Regarde devant toi, pas tes pieds"],
    breathingCue: "Respire librement, sans bloquer.",
    bodyAreas: ["legs", "core"],
    repeatability: "normal",
  },
  {
    id: "supported-tandem-stance",
    name: "Position tandem avec appui",
    category: "balance",
    description: "Un pied devant l'autre, comme sur une ligne, pour muscler l'équilibre statique.",
    startingPosition: "Debout près d'un support (chaise ou mur), place un pied juste devant l'autre, comme sur une ligne.",
    instructions: [
      "Maintiens la position, avec un appui léger sur le support si besoin.",
      "Change de pied devant, puis recommence.",
    ],
    durationSeconds: 15,
    position: "supported",
    requiredEquipment: ["chair"],
    difficulty: 2,
    lowImpact: true,
    illustrationKey: "supported-tandem-stance",
    primaryBenefits: ["Équilibre", "Stabilité"],
    cues: ["Fixe un point devant toi", "Garde le support à portée de main"],
    breathingCue: "Respire calmement pendant le maintien.",
    bodyAreas: ["legs", "core"],
    repeatability: "normal",
  },
];
