import type { MoveExercise } from "../../shared/types";

export const balanceExercises: MoveExercise[] = [
  {
    id: "weight-shift",
    name: "Transfert de poids",
    category: "balance",
    description: "La base du travail d'équilibre : déplacer son poids d'un pied à l'autre en confiance.",
    instructions: [
      "Debout, pieds à largeur des hanches, mains sur une chaise si besoin.",
      "Transfère doucement ton poids sur le pied droit, puis sur le pied gauche.",
    ],
    repetitions: 8,
    position: "supported",
    requiredEquipment: ["chair"],
    difficulty: 1,
    lowImpact: true,
    illustrationKey: "weight-shift",
    primaryBenefits: ["Équilibre", "Confiance dans les appuis"],
    bodyAreas: ["legs", "core"],
    repeatability: "frequent",
  },
  {
    id: "assisted-single-leg-balance",
    name: "Équilibre assisté sur un pied",
    category: "balance",
    description: "Travaille l'équilibre unipodal en toute sécurité, avec un appui à disposition.",
    instructions: [
      "Debout près d'une chaise, tiens légèrement le dossier.",
      "Lève un pied de quelques centimètres du sol.",
      "Maintiens la position, puis change de côté.",
    ],
    durationSeconds: 15,
    position: "supported",
    requiredEquipment: ["chair"],
    difficulty: 2,
    lowImpact: true,
    avoidWith: ["ankles"],
    easierVariation: "Garde les orteils du pied levé au contact du sol.",
    harderVariation: "Relâche légèrement l'appui sur la chaise.",
    illustrationKey: "assisted-single-leg-balance",
    primaryBenefits: ["Équilibre", "Stabilité des chevilles"],
    bodyAreas: ["legs", "core"],
    repeatability: "normal",
  },
  {
    id: "assisted-heel-to-toe-walk",
    name: "Marche talon-pointe assistée",
    category: "balance",
    description: "Une marche en ligne, talon contre pointe, pour travailler la précision des appuis.",
    instructions: [
      "Longe un mur ou un plan de travail pour pouvoir t'appuyer.",
      "Avance en posant le talon juste devant les orteils de l'autre pied.",
    ],
    repetitions: 8,
    position: "supported",
    requiredEquipment: [],
    difficulty: 2,
    lowImpact: true,
    avoidWith: ["ankles"],
    easierVariation: "Laisse un petit espace entre le talon et la pointe.",
    illustrationKey: "assisted-heel-to-toe-walk",
    primaryBenefits: ["Équilibre", "Précision des appuis"],
    bodyAreas: ["legs", "core"],
    repeatability: "normal",
  },
  {
    id: "supported-tandem-stance",
    name: "Position tandem avec appui",
    category: "balance",
    description: "Un pied devant l'autre, comme sur une ligne, pour muscler l'équilibre statique.",
    instructions: [
      "Debout près d'un support, place un pied juste devant l'autre.",
      "Maintiens la position quelques secondes, puis change de pied devant.",
    ],
    durationSeconds: 15,
    position: "supported",
    requiredEquipment: ["chair"],
    difficulty: 2,
    lowImpact: true,
    illustrationKey: "supported-tandem-stance",
    primaryBenefits: ["Équilibre", "Stabilité"],
    bodyAreas: ["legs", "core"],
    repeatability: "normal",
  },
];
