import type { MoveExercise } from "../../shared/types";

export const cardioExercises: MoveExercise[] = [
  {
    id: "march-in-place",
    name: "Marche sur place",
    category: "cardio",
    description: "Le mouvement cardio le plus simple pour faire circuler le sang en douceur.",
    startingPosition: "Debout, pieds écartés de la largeur des hanches, bras détendus le long du corps.",
    instructions: [
      "Marche sur place à un rythme confortable.",
      "Balance les bras naturellement au fil du mouvement.",
    ],
    durationSeconds: 30,
    position: "standing",
    requiredEquipment: [],
    difficulty: 1,
    lowImpact: true,
    easierVariation: "Ralentis le rythme ou tiens-toi à une chaise.",
    harderVariation: "Monte les genoux un peu plus haut.",
    illustrationKey: "march-in-place",
    primaryBenefits: ["Cardio doux", "Échauffement"],
    cues: ["Garde le buste droit", "Pose le pied bien à plat à chaque pas"],
    breathingCue: "Respire à ton rythme, sans bloquer.",
    bodyAreas: ["legs", "full_body"],
    repeatability: "daily",
  },
  {
    id: "step-touch",
    name: "Step-touch",
    category: "cardio",
    description: "Un pas de côté simple et rythmé pour activer le corps entier.",
    startingPosition: "Debout, pieds joints, bras détendus le long du corps.",
    instructions: [
      "Fais un pas sur le côté avec un pied.",
      "Ramène l'autre pied contre lui.",
      "Répète de l'autre côté, en alternant.",
    ],
    durationSeconds: 30,
    position: "standing",
    requiredEquipment: [],
    difficulty: 1,
    lowImpact: true,
    easierVariation: "Réduis l'amplitude des pas.",
    illustrationKey: "step-touch",
    primaryBenefits: ["Cardio doux", "Coordination"],
    cues: ["Garde les genoux légèrement souples", "Regarde devant toi pour rester stable"],
    breathingCue: "Respire librement, sans bloquer.",
    bodyAreas: ["legs", "full_body"],
    repeatability: "frequent",
  },
  {
    id: "side-steps",
    name: "Pas latéraux",
    category: "cardio",
    description: "Déplacements latéraux contrôlés pour travailler le cardio et la coordination.",
    startingPosition: "Debout, pieds à largeur des hanches, genoux légèrement fléchis.",
    instructions: [
      "Fais 4 pas vers la droite.",
      "Fais 4 pas vers la gauche.",
      "Continue en alternant les deux côtés.",
    ],
    durationSeconds: 30,
    position: "standing",
    requiredEquipment: [],
    difficulty: 1,
    lowImpact: true,
    easierVariation: "Réduis le nombre de pas dans chaque direction.",
    illustrationKey: "side-steps",
    primaryBenefits: ["Cardio doux", "Coordination"],
    cues: ["Garde le buste droit", "Pose les pieds bien à plat"],
    breathingCue: "Respire librement, sans bloquer.",
    bodyAreas: ["legs", "full_body"],
    repeatability: "frequent",
  },
  {
    id: "active-arm-march",
    name: "Marche bras actifs",
    category: "cardio",
    description: "Marche sur place en activant davantage les bras pour intensifier légèrement l'effort.",
    startingPosition: "Debout, pieds écartés de la largeur des hanches, bras pliés devant toi.",
    instructions: [
      "Marche sur place en levant les bras devant toi à chaque pas.",
      "Garde un rythme régulier et confortable.",
    ],
    durationSeconds: 30,
    position: "standing",
    requiredEquipment: [],
    difficulty: 2,
    lowImpact: true,
    easierVariation: "Garde les bras plus bas.",
    illustrationKey: "active-arm-march",
    primaryBenefits: ["Cardio doux", "Coordination"],
    cues: ["Garde un rythme régulier", "Épaules détendues, loin des oreilles"],
    breathingCue: "Respire librement, sans bloquer.",
    bodyAreas: ["full_body", "arms"],
    repeatability: "frequent",
  },
  {
    id: "gentle-knee-lift",
    name: "Marche genoux légèrement relevés",
    category: "cardio",
    description: "Une marche sur place avec des genoux un peu plus hauts, pour intensifier doucement.",
    startingPosition: "Debout, pieds écartés de la largeur des hanches, bras détendus le long du corps.",
    instructions: [
      "Marche sur place en relevant légèrement les genoux.",
      "Garde le buste droit et stable pendant le mouvement.",
    ],
    durationSeconds: 30,
    position: "standing",
    requiredEquipment: [],
    difficulty: 2,
    lowImpact: true,
    avoidWith: ["hips"],
    easierVariation: "Relève les genoux moins haut.",
    illustrationKey: "gentle-knee-lift",
    primaryBenefits: ["Cardio doux", "Force des jambes"],
    cues: ["Garde le buste droit et stable", "Relève les genoux sans te pencher en arrière"],
    breathingCue: "Respire librement, sans bloquer.",
    bodyAreas: ["legs", "hips"],
    repeatability: "normal",
  },
  {
    id: "gentle-heel-to-glute",
    name: "Talons-fesses doux",
    category: "cardio",
    description: "Amène doucement les talons vers les fessiers en marchant sur place.",
    startingPosition: "Debout, pieds écartés de la largeur des hanches, bras détendus.",
    instructions: [
      "Marche sur place en amenant un talon vers l'arrière à chaque pas.",
      "Reste sur un rythme confortable.",
    ],
    durationSeconds: 30,
    position: "standing",
    requiredEquipment: [],
    difficulty: 2,
    lowImpact: true,
    avoidWith: ["knees"],
    easierVariation: "Réduis l'amplitude du mouvement.",
    illustrationKey: "gentle-heel-to-glute",
    primaryBenefits: ["Cardio doux", "Souplesse des jambes"],
    cues: ["Garde les genoux proches l'un de l'autre", "Reste sur un rythme confortable"],
    breathingCue: "Respire librement, sans bloquer.",
    bodyAreas: ["legs"],
    repeatability: "normal",
  },
  {
    id: "controlled-forward-backward-walk",
    name: "Marche avant/arrière contrôlée",
    category: "cardio",
    description: "Un déplacement avant-arrière sur quelques pas, pour le cardio et l'équilibre.",
    startingPosition: "Debout, pieds joints, dans un espace dégagé devant et derrière toi.",
    instructions: [
      "Fais 3 pas vers l'avant, avec contrôle.",
      "Fais 3 pas vers l'arrière, avec contrôle.",
      "Continue en alternant.",
    ],
    durationSeconds: 30,
    position: "standing",
    requiredEquipment: [],
    difficulty: 2,
    lowImpact: true,
    easierVariation: "Réduis le nombre de pas.",
    illustrationKey: "controlled-forward-backward-walk",
    primaryBenefits: ["Cardio doux", "Équilibre"],
    cues: ["Garde les yeux devant toi pour rester stable", "Pose chaque pas avec contrôle"],
    breathingCue: "Respire librement, sans bloquer.",
    bodyAreas: ["legs", "full_body"],
    repeatability: "normal",
  },
];
