import type { MoveExercise } from "../../shared/types";

export const cardioExercises: MoveExercise[] = [
  {
    id: "march-in-place",
    name: "Marche sur place",
    category: "cardio",
    description: "Le mouvement cardio le plus simple pour faire circuler le sang en douceur.",
    instructions: [
      "Debout, marche sur place à un rythme confortable.",
      "Balance les bras naturellement.",
    ],
    durationSeconds: 30,
    position: "standing",
    requiredEquipment: [],
    difficulty: 1,
    lowImpact: true,
    easierVariation: "Ralentis le rythme ou tiens-toi à une chaise.",
    harderVariation: "Monte les genoux un peu plus haut.",
    illustrationKey: "march-in-place",
    primaryBenefits: ["Cardio doux", "Échauffement"],
    breathingCue: "Respire à ton rythme.",
    bodyAreas: ["legs", "full_body"],
    repeatability: "daily",
  },
  {
    id: "step-touch",
    name: "Step-touch",
    category: "cardio",
    description: "Un pas de côté simple et rythmé pour activer le corps entier.",
    instructions: [
      "Fais un pas sur le côté avec un pied, puis ramène l'autre pied contre lui.",
      "Répète de l'autre côté, en alternant.",
    ],
    durationSeconds: 30,
    position: "standing",
    requiredEquipment: [],
    difficulty: 1,
    lowImpact: true,
    easierVariation: "Réduis l'amplitude des pas.",
    illustrationKey: "step-touch",
    primaryBenefits: ["Cardio doux", "Coordination"],
    bodyAreas: ["legs", "full_body"],
    repeatability: "frequent",
  },
  {
    id: "side-steps",
    name: "Pas latéraux",
    category: "cardio",
    description: "Déplacements latéraux contrôlés pour travailler le cardio et la coordination.",
    instructions: [
      "Fais 4 pas vers la droite, puis 4 pas vers la gauche.",
      "Garde les genoux légèrement souples.",
    ],
    durationSeconds: 30,
    position: "standing",
    requiredEquipment: [],
    difficulty: 1,
    lowImpact: true,
    easierVariation: "Réduis le nombre de pas dans chaque direction.",
    illustrationKey: "side-steps",
    primaryBenefits: ["Cardio doux", "Coordination"],
    bodyAreas: ["legs", "full_body"],
    repeatability: "frequent",
  },
  {
    id: "active-arm-march",
    name: "Marche bras actifs",
    category: "cardio",
    description: "Marche sur place en activant davantage les bras pour intensifier légèrement l'effort.",
    instructions: [
      "Marche sur place en levant les bras devant toi à chaque pas.",
      "Garde un rythme régulier et confortable.",
    ],
    durationSeconds: 30,
    position: "standing",
    requiredEquipment: [],
    difficulty: 2,
    lowImpact: true,
    easierVariation: "Garde les bras plus bas.",
    illustrationKey: "active-arm-march",
    primaryBenefits: ["Cardio doux", "Coordination"],
    bodyAreas: ["full_body", "arms"],
    repeatability: "frequent",
  },
  {
    id: "gentle-knee-lift",
    name: "Marche genoux légèrement relevés",
    category: "cardio",
    description: "Une marche sur place avec des genoux un peu plus hauts, pour intensifier doucement.",
    instructions: [
      "Marche sur place en relevant légèrement les genoux.",
      "Garde le buste droit et stable.",
    ],
    durationSeconds: 30,
    position: "standing",
    requiredEquipment: [],
    difficulty: 2,
    lowImpact: true,
    avoidWith: ["hips"],
    easierVariation: "Relève les genoux moins haut.",
    illustrationKey: "gentle-knee-lift",
    primaryBenefits: ["Cardio doux", "Force des jambes"],
    bodyAreas: ["legs", "hips"],
    repeatability: "normal",
  },
  {
    id: "gentle-heel-to-glute",
    name: "Talons-fesses doux",
    category: "cardio",
    description: "Amène doucement les talons vers les fessiers en marchant sur place.",
    instructions: [
      "Marche sur place en amenant un talon vers l'arrière à chaque pas.",
      "Reste sur un rythme confortable.",
    ],
    durationSeconds: 30,
    position: "standing",
    requiredEquipment: [],
    difficulty: 2,
    lowImpact: true,
    avoidWith: ["knees"],
    easierVariation: "Réduis l'amplitude du mouvement.",
    illustrationKey: "gentle-heel-to-glute",
    primaryBenefits: ["Cardio doux", "Souplesse des jambes"],
    bodyAreas: ["legs"],
    repeatability: "normal",
  },
  {
    id: "controlled-forward-backward-walk",
    name: "Marche avant/arrière contrôlée",
    category: "cardio",
    description: "Un déplacement avant-arrière sur quelques pas, pour le cardio et l'équilibre.",
    instructions: [
      "Fais 3 pas vers l'avant, puis 3 pas vers l'arrière avec contrôle.",
      "Garde les yeux devant toi pour rester stable.",
    ],
    durationSeconds: 30,
    position: "standing",
    requiredEquipment: [],
    difficulty: 2,
    lowImpact: true,
    easierVariation: "Réduis le nombre de pas.",
    illustrationKey: "controlled-forward-backward-walk",
    primaryBenefits: ["Cardio doux", "Équilibre"],
    bodyAreas: ["legs", "full_body"],
    repeatability: "normal",
  },
];
