import type { MoveExercise } from "../../shared/types";

export const mobilityExercises: MoveExercise[] = [
  {
    id: "shoulder-rolls",
    name: "Rotations des épaules",
    category: "mobility",
    description: "Détend les épaules et relâche les tensions du haut du corps.",
    startingPosition: "Assise ou debout, bras détendus le long du corps, épaules relâchées.",
    instructions: [
      "Fais rouler les épaules vers l'arrière lentement.",
      "Inverse le sens, vers l'avant.",
    ],
    repetitions: 8,
    position: "seated",
    requiredEquipment: [],
    difficulty: 1,
    lowImpact: true,
    illustrationKey: "shoulder-rolls",
    primaryBenefits: ["Mobilité des épaules", "Relâchement"],
    cues: ["Garde les mouvements lents et amples", "Détends les bras pendant tout l'exercice"],
    breathingCue: "Respire calmement, sans bloquer.",
    bodyAreas: ["shoulders"],
    repeatability: "daily",
  },
  {
    id: "chest-opening-stretch",
    name: "Ouverture de poitrine",
    category: "mobility",
    description: "Ouvre la cage thoracique pour contrer la posture voûtée.",
    startingPosition: "Assise ou debout, dos droit.",
    instructions: [
      "Joins les mains derrière le dos si possible, ou ouvre simplement les bras en croix.",
      "Redresse la poitrine vers le haut en douceur.",
      "Maintiens quelques secondes.",
    ],
    durationSeconds: 20,
    position: "seated",
    requiredEquipment: [],
    difficulty: 1,
    lowImpact: true,
    illustrationKey: "chest-opening-stretch",
    primaryBenefits: ["Posture", "Souplesse thoracique"],
    cues: ["Garde les épaules basses", "N'insiste jamais dans une position inconfortable"],
    breathingCue: "Inspire en ouvrant la poitrine, respire calmement pendant le maintien.",
    bodyAreas: ["chest", "shoulders", "back"],
    repeatability: "frequent",
  },
  {
    id: "seated-thoracic-rotation",
    name: "Rotations thoraciques assises",
    category: "mobility",
    description: "Fait tourner doucement le haut du dos pour gagner en souplesse.",
    startingPosition: "Assise bien droite au bord de la chaise, bras croisés sur la poitrine.",
    instructions: [
      "Tourne le buste doucement vers la droite.",
      "Reviens au centre.",
      "Tourne vers la gauche.",
    ],
    repetitions: 8,
    position: "seated",
    requiredEquipment: ["chair"],
    difficulty: 1,
    lowImpact: true,
    illustrationKey: "seated-thoracic-rotation",
    primaryBenefits: ["Mobilité du dos", "Souplesse"],
    cues: ["Garde le bassin stable, seul le buste tourne", "Mouvement lent, sans à-coups"],
    breathingCue: "Expire en tournant, inspire en revenant au centre.",
    bodyAreas: ["back"],
    repeatability: "frequent",
  },
  {
    id: "ankle-mobility",
    name: "Mobilité de cheville",
    category: "mobility",
    description: "Réveille les chevilles, utile avant la marche ou le cardio.",
    startingPosition: "Assise, dos droit, un pied légèrement levé du sol.",
    instructions: [
      "Lève une pointe de pied.",
      "Fais des cercles avec la cheville, dans un sens puis dans l'autre.",
      "Répète de l'autre côté.",
    ],
    repetitions: 8,
    position: "seated",
    requiredEquipment: [],
    difficulty: 1,
    lowImpact: true,
    illustrationKey: "ankle-mobility",
    primaryBenefits: ["Mobilité des chevilles"],
    cues: ["Mouvement lent et contrôlé", "Amplitude confortable, sans forcer"],
    breathingCue: "Respire librement, sans bloquer.",
    bodyAreas: ["calves"],
    repeatability: "daily",
  },
  {
    id: "hip-mobility-circles",
    name: "Mobilisation des hanches",
    category: "mobility",
    description: "Cercles doux des hanches pour gagner en aisance de mouvement.",
    startingPosition: "Debout, mains sur les hanches ou sur une chaise pour l'équilibre.",
    instructions: [
      "Fais de petits cercles avec le bassin dans un sens.",
      "Puis dans l'autre sens.",
    ],
    repetitions: 6,
    position: "standing",
    requiredEquipment: [],
    difficulty: 1,
    lowImpact: true,
    illustrationKey: "hip-mobility-circles",
    primaryBenefits: ["Mobilité des hanches"],
    cues: ["Garde les genoux légèrement souples", "Mouvement petit et contrôlé"],
    breathingCue: "Respire librement, sans bloquer.",
    bodyAreas: ["hips"],
    repeatability: "frequent",
  },
  {
    id: "seated-spine-flexion-extension",
    name: "Flexion-extension douce du dos assis",
    category: "mobility",
    description: "Un mouvement doux façon chat-vache, en position assise.",
    startingPosition: "Assise, mains posées sur les genoux, dos droit.",
    instructions: [
      "Arrondis doucement le dos en expirant.",
      "Creuse légèrement le dos en inspirant.",
    ],
    repetitions: 8,
    position: "seated",
    requiredEquipment: ["chair"],
    difficulty: 1,
    lowImpact: true,
    illustrationKey: "seated-spine-flexion-extension",
    primaryBenefits: ["Mobilité du dos", "Détente"],
    cues: ["Mouvement lent, sans à-coups", "Reste dans une amplitude confortable"],
    breathingCue: "Expire en arrondissant, inspire en creusant.",
    bodyAreas: ["back", "core"],
    repeatability: "frequent",
  },
  {
    id: "arm-opening-stretch",
    name: "Ouverture des bras",
    category: "mobility",
    description: "Étire doucement les bras et les épaules dans toute leur amplitude.",
    startingPosition: "Debout, bras détendus le long du corps.",
    instructions: [
      "Lève les bras devant toi.",
      "Ouvre-les largement sur les côtés.",
      "Reviens avec contrôle.",
    ],
    repetitions: 8,
    position: "standing",
    requiredEquipment: [],
    difficulty: 1,
    lowImpact: true,
    illustrationKey: "arm-opening-stretch",
    primaryBenefits: ["Mobilité des épaules"],
    cues: ["Garde les épaules basses", "Mouvement ample mais sans forcer"],
    breathingCue: "Inspire en ouvrant les bras, souffle en les ramenant.",
    bodyAreas: ["shoulders", "arms"],
    repeatability: "frequent",
  },
  {
    id: "gentle-neck-rotation",
    name: "Rotation cervicale douce",
    category: "mobility",
    description: "Relâche les tensions de la nuque avec un mouvement lent et contrôlé.",
    startingPosition: "Assise bien droite, épaules détendues.",
    instructions: [
      "Tourne doucement la tête vers la droite.",
      "Reviens au centre.",
      "Tourne vers la gauche.",
    ],
    repetitions: 6,
    position: "seated",
    requiredEquipment: [],
    difficulty: 1,
    lowImpact: true,
    illustrationKey: "gentle-neck-rotation",
    primaryBenefits: ["Détente de la nuque"],
    cues: ["Reste toujours dans une amplitude confortable, sans forcer", "Mouvement lent et contrôlé"],
    breathingCue: "Respire calmement pendant le mouvement.",
    bodyAreas: ["shoulders"],
    repeatability: "daily",
  },
];
