import type { MoveExercise } from "../../shared/types";

export const mobilityExercises: MoveExercise[] = [
  {
    id: "shoulder-rolls",
    name: "Rotations des épaules",
    category: "mobility",
    description: "Détend les épaules et relâche les tensions du haut du corps.",
    instructions: [
      "Assise ou debout, fais rouler les épaules vers l'arrière lentement.",
      "Puis inverse le sens, vers l'avant.",
    ],
    repetitions: 8,
    position: "seated",
    requiredEquipment: [],
    difficulty: 1,
    lowImpact: true,
    illustrationKey: "shoulder-rolls",
    primaryBenefits: ["Mobilité des épaules", "Relâchement"],
    bodyAreas: ["shoulders"],
    repeatability: "daily",
  },
  {
    id: "chest-opening-stretch",
    name: "Ouverture de poitrine",
    category: "mobility",
    description: "Ouvre la cage thoracique pour contrer la posture voûtée.",
    instructions: [
      "Joins les mains derrière le dos si possible, ou ouvre simplement les bras en croix.",
      "Redresse la poitrine vers le haut en douceur.",
    ],
    durationSeconds: 20,
    position: "seated",
    requiredEquipment: [],
    difficulty: 1,
    lowImpact: true,
    illustrationKey: "chest-opening-stretch",
    primaryBenefits: ["Posture", "Souplesse thoracique"],
    bodyAreas: ["chest", "shoulders", "back"],
    repeatability: "frequent",
  },
  {
    id: "seated-thoracic-rotation",
    name: "Rotations thoraciques assises",
    category: "mobility",
    description: "Fait tourner doucement le haut du dos pour gagner en souplesse.",
    instructions: [
      "Assise bien droite, bras croisés sur la poitrine.",
      "Tourne le buste doucement vers la droite, puis vers la gauche.",
    ],
    repetitions: 8,
    position: "seated",
    requiredEquipment: ["chair"],
    difficulty: 1,
    lowImpact: true,
    illustrationKey: "seated-thoracic-rotation",
    primaryBenefits: ["Mobilité du dos", "Souplesse"],
    bodyAreas: ["back"],
    repeatability: "frequent",
  },
  {
    id: "ankle-mobility",
    name: "Mobilité de cheville",
    category: "mobility",
    description: "Réveille les chevilles, utile avant la marche ou le cardio.",
    instructions: [
      "Assise, lève une pointe de pied puis fais des cercles avec la cheville.",
      "Répète de l'autre côté.",
    ],
    repetitions: 8,
    position: "seated",
    requiredEquipment: [],
    difficulty: 1,
    lowImpact: true,
    illustrationKey: "ankle-mobility",
    primaryBenefits: ["Mobilité des chevilles"],
    bodyAreas: ["calves"],
    repeatability: "daily",
  },
  {
    id: "hip-mobility-circles",
    name: "Mobilisation des hanches",
    category: "mobility",
    description: "Cercles doux des hanches pour gagner en aisance de mouvement.",
    instructions: [
      "Debout, mains sur les hanches ou sur une chaise pour l'équilibre.",
      "Fais de petits cercles avec le bassin, dans un sens puis dans l'autre.",
    ],
    repetitions: 6,
    position: "standing",
    requiredEquipment: [],
    difficulty: 1,
    lowImpact: true,
    illustrationKey: "hip-mobility-circles",
    primaryBenefits: ["Mobilité des hanches"],
    bodyAreas: ["hips"],
    repeatability: "frequent",
  },
  {
    id: "seated-spine-flexion-extension",
    name: "Flexion-extension douce du dos assis",
    category: "mobility",
    description: "Un mouvement doux façon chat-vache, en position assise.",
    instructions: [
      "Assise, mains sur les genoux.",
      "Arrondis doucement le dos en expirant, puis creuse-le légèrement en inspirant.",
    ],
    repetitions: 8,
    position: "seated",
    requiredEquipment: ["chair"],
    difficulty: 1,
    lowImpact: true,
    illustrationKey: "seated-spine-flexion-extension",
    primaryBenefits: ["Mobilité du dos", "Détente"],
    breathingCue: "Expire en arrondissant, inspire en creusant.",
    bodyAreas: ["back", "core"],
    repeatability: "frequent",
  },
  {
    id: "arm-opening-stretch",
    name: "Ouverture des bras",
    category: "mobility",
    description: "Étire doucement les bras et les épaules dans toute leur amplitude.",
    instructions: [
      "Lève les bras devant toi puis ouvre-les largement sur les côtés.",
      "Reviens avec contrôle.",
    ],
    repetitions: 8,
    position: "standing",
    requiredEquipment: [],
    difficulty: 1,
    lowImpact: true,
    illustrationKey: "arm-opening-stretch",
    primaryBenefits: ["Mobilité des épaules"],
    bodyAreas: ["shoulders", "arms"],
    repeatability: "frequent",
  },
  {
    id: "gentle-neck-rotation",
    name: "Rotation cervicale douce",
    category: "mobility",
    description: "Relâche les tensions de la nuque avec un mouvement lent et contrôlé.",
    instructions: [
      "Assise bien droite, tourne doucement la tête vers la droite.",
      "Reviens au centre, puis tourne vers la gauche.",
    ],
    repetitions: 6,
    position: "seated",
    requiredEquipment: [],
    difficulty: 1,
    lowImpact: true,
    illustrationKey: "gentle-neck-rotation",
    primaryBenefits: ["Détente de la nuque"],
    cues: ["Reste toujours dans une amplitude confortable, sans forcer."],
    bodyAreas: ["shoulders"],
    repeatability: "daily",
  },
];
