import type { MoveExercise } from "../../shared/types";

export const pilatesExercises: MoveExercise[] = [
  {
    id: "diaphragmatic-breathing",
    name: "Respiration diaphragmatique",
    category: "pilates",
    description: "La base du contrôle du corps : une respiration profonde et consciente.",
    startingPosition: "Assise confortablement, ou allongée sur le dos, une main posée sur le ventre.",
    instructions: [
      "Inspire lentement par le nez en gonflant le ventre sous ta main.",
      "Expire lentement par la bouche en rentrant doucement le ventre.",
    ],
    durationSeconds: 30,
    position: "seated",
    requiredEquipment: [],
    difficulty: 1,
    lowImpact: true,
    illustrationKey: "diaphragmatic-breathing",
    primaryBenefits: ["Détente", "Contrôle respiratoire"],
    cues: ["Garde les épaules détendues", "Ne force jamais la respiration"],
    breathingCue: "Inspire par le nez, expire lentement par la bouche.",
    bodyAreas: ["core"],
    repeatability: "daily",
  },
  {
    id: "pelvic-tilt",
    name: "Bascule du bassin",
    category: "pilates",
    description: "Mobilise et stabilise le bassin, allongée au sol.",
    startingPosition: "Allongée sur le dos, genoux pliés, pieds à plat au sol, écartés de la largeur du bassin.",
    instructions: [
      "Bascule doucement le bassin pour plaquer le bas du dos au sol.",
      "Relâche avec contrôle.",
    ],
    repetitions: 8,
    position: "floor",
    requiredEquipment: ["mat"],
    difficulty: 1,
    lowImpact: true,
    illustrationKey: "pelvic-tilt",
    primaryBenefits: ["Stabilité du bassin", "Sangle abdominale"],
    cues: ["Garde les épaules détendues au sol", "Mouvement petit, pas besoin de forcer"],
    breathingCue: "Expire en basculant le bassin, inspire en relâchant.",
    bodyAreas: ["core", "back", "hips"],
    repeatability: "frequent",
  },
  {
    id: "simplified-dead-bug",
    name: "Dead bug simplifié",
    category: "pilates",
    description: "Un mouvement de contrôle du centre du corps, bras et jambes en alternance.",
    startingPosition: "Allongée sur le dos, genoux pliés à 90°, bras tendus vers le plafond.",
    instructions: [
      "Abaisse doucement un bras derrière la tête tout en gardant le dos stable et plaqué au sol.",
      "Reviens à la position de départ.",
      "Change de côté.",
    ],
    repetitions: 6,
    position: "floor",
    requiredEquipment: ["mat"],
    difficulty: 2,
    lowImpact: true,
    avoidWith: ["back"],
    easierVariation: "Bouge un seul bras à la fois, sans les jambes.",
    illustrationKey: "simplified-dead-bug",
    primaryBenefits: ["Sangle abdominale", "Stabilité du dos"],
    cues: ["Garde le bas du dos plaqué au sol tout du long", "Mouvement lent et contrôlé"],
    breathingCue: "Souffle en abaissant le bras, inspire en revenant.",
    bodyAreas: ["core"],
    repeatability: "recovery_sensitive",
  },
  {
    id: "gentle-abdominal-activation",
    name: "Activation abdominale douce",
    category: "pilates",
    description: "Un exercice statique pour réveiller la sangle abdominale profonde.",
    startingPosition: "Allongée sur le dos, genoux pliés, pieds à plat au sol.",
    instructions: [
      "Rentre doucement le nombril vers la colonne, sans bloquer la respiration.",
      "Maintiens quelques secondes.",
      "Relâche.",
    ],
    durationSeconds: 15,
    position: "floor",
    requiredEquipment: ["mat"],
    difficulty: 1,
    lowImpact: true,
    illustrationKey: "gentle-abdominal-activation",
    primaryBenefits: ["Sangle abdominale"],
    cues: ["Ne bloque jamais ta respiration", "Contraction douce, pas maximale"],
    breathingCue: "Respire normalement pendant le maintien.",
    bodyAreas: ["core"],
    repeatability: "frequent",
  },
  {
    id: "controlled-lying-knee-opening",
    name: "Ouverture de genou allongée contrôlée",
    category: "pilates",
    description: "Renforce et stabilise les hanches en gardant le bassin immobile.",
    startingPosition: "Allongée sur le côté, genoux pliés l'un sur l'autre, tête posée sur le bras ou un coussin.",
    instructions: [
      "Ouvre le genou du dessus vers le plafond, sans bouger le bassin.",
      "Referme avec contrôle.",
      "Répète, puis change de côté.",
    ],
    repetitions: 8,
    position: "floor",
    requiredEquipment: ["mat"],
    difficulty: 2,
    lowImpact: true,
    avoidWith: ["hips"],
    easierVariation: "Réduis l'amplitude d'ouverture du genou.",
    illustrationKey: "controlled-lying-knee-opening",
    primaryBenefits: ["Stabilité des hanches"],
    cues: ["Garde le bassin immobile pendant tout le mouvement", "Les pieds restent collés l'un à l'autre"],
    breathingCue: "Expire en ouvrant le genou, inspire en refermant.",
    bodyAreas: ["hips", "core", "glutes"],
    repeatability: "normal",
  },
];
