import type { MoveExercise } from "../../shared/types";

export const pilatesExercises: MoveExercise[] = [
  {
    id: "diaphragmatic-breathing",
    name: "Respiration diaphragmatique",
    category: "pilates",
    description: "La base du contrôle du corps : une respiration profonde et consciente.",
    instructions: [
      "Assise ou allongée, une main sur le ventre.",
      "Inspire en gonflant le ventre, expire en le rentrant doucement.",
    ],
    durationSeconds: 30,
    position: "seated",
    requiredEquipment: [],
    difficulty: 1,
    lowImpact: true,
    illustrationKey: "diaphragmatic-breathing",
    primaryBenefits: ["Détente", "Contrôle respiratoire"],
    breathingCue: "Inspire par le nez, expire lentement par la bouche.",
    bodyAreas: ["core"],
    repeatability: "daily",
  },
  {
    id: "pelvic-tilt",
    name: "Bascule du bassin",
    category: "pilates",
    description: "Mobilise et stabilise le bassin, allongée au sol.",
    instructions: [
      "Allongée sur le dos, genoux pliés, pieds au sol.",
      "Bascule doucement le bassin pour plaquer le bas du dos au sol, puis relâche.",
    ],
    repetitions: 8,
    position: "floor",
    requiredEquipment: ["mat"],
    difficulty: 1,
    lowImpact: true,
    illustrationKey: "pelvic-tilt",
    primaryBenefits: ["Stabilité du bassin", "Sangle abdominale"],
    breathingCue: "Expire en basculant le bassin.",
    bodyAreas: ["core", "back", "hips"],
    repeatability: "frequent",
  },
  {
    id: "simplified-dead-bug",
    name: "Dead bug simplifié",
    category: "pilates",
    description: "Un mouvement de contrôle du centre du corps, bras et jambes en alternance.",
    instructions: [
      "Allongée sur le dos, genoux pliés à 90°, bras tendus vers le plafond.",
      "Abaisse doucement un bras derrière la tête tout en gardant le dos stable.",
      "Reviens, puis change de côté.",
    ],
    repetitions: 6,
    position: "floor",
    requiredEquipment: ["mat"],
    difficulty: 2,
    lowImpact: true,
    avoidWith: ["back"],
    easierVariation: "Bouge un seul bras à la fois, sans les jambes.",
    illustrationKey: "simplified-dead-bug",
    primaryBenefits: ["Sangle abdominale", "Stabilité du dos"],
    breathingCue: "Souffle en abaissant le bras.",
    bodyAreas: ["core"],
    repeatability: "recovery_sensitive",
  },
  {
    id: "gentle-abdominal-activation",
    name: "Activation abdominale douce",
    category: "pilates",
    description: "Un exercice statique pour réveiller la sangle abdominale profonde.",
    instructions: [
      "Allongée sur le dos, genoux pliés.",
      "Rentre doucement le nombril vers la colonne, sans bloquer la respiration.",
      "Maintiens quelques secondes, puis relâche.",
    ],
    durationSeconds: 15,
    position: "floor",
    requiredEquipment: ["mat"],
    difficulty: 1,
    lowImpact: true,
    illustrationKey: "gentle-abdominal-activation",
    primaryBenefits: ["Sangle abdominale"],
    breathingCue: "Respire normalement pendant le maintien.",
    bodyAreas: ["core"],
    repeatability: "frequent",
  },
  {
    id: "controlled-lying-knee-opening",
    name: "Ouverture de genou allongée contrôlée",
    category: "pilates",
    description: "Renforce et stabilise les hanches en gardant le bassin immobile.",
    instructions: [
      "Allongée sur le côté, genoux pliés l'un sur l'autre.",
      "Ouvre le genou du dessus vers le plafond, sans bouger le bassin.",
      "Referme avec contrôle.",
    ],
    repetitions: 8,
    position: "floor",
    requiredEquipment: ["mat"],
    difficulty: 2,
    lowImpact: true,
    avoidWith: ["hips"],
    easierVariation: "Réduis l'amplitude d'ouverture du genou.",
    illustrationKey: "controlled-lying-knee-opening",
    primaryBenefits: ["Stabilité des hanches"],
    bodyAreas: ["hips", "core", "glutes"],
    repeatability: "normal",
  },
];
