import type { MoveExercise } from "../../shared/types";

export const strengthExercises: MoveExercise[] = [
  {
    id: "sit-to-stand",
    name: "Assis-debout",
    category: "strength",
    description:
      "L'exercice de base pour retrouver de la force dans les jambes, à partir d'une chaise.",
    startingPosition:
      "Assieds-toi au bord de la chaise, pieds à largeur des hanches, bien à plat au sol.",
    instructions: [
      "Penche légèrement le buste vers l'avant.",
      "Pousse dans tes jambes pour te relever complètement.",
      "Rassieds-toi ensuite avec contrôle, sans te laisser tomber.",
    ],
    repetitions: 8,
    position: "seated",
    requiredEquipment: ["chair"],
    difficulty: 1,
    lowImpact: true,
    easierVariation: "Prends légèrement appui sur les mains ou les accoudoirs.",
    harderVariation: "Ralentis la descente sur 3 secondes.",
    illustrationKey: "sit-to-stand",
    primaryBenefits: ["Force des jambes", "Autonomie au quotidien"],
    cues: ["Regarde loin devant toi", "Talons bien ancrés au sol", "Garde le dos droit en te relevant"],
    breathingCue: "Souffle en te levant, inspire en te rasseyant.",
    bodyAreas: ["legs", "glutes"],
    repeatability: "frequent",
  },
  {
    id: "chair-half-squat",
    name: "Demi-squat avec chaise",
    category: "strength",
    description: "Un mouvement de squat guidé par la présence rassurante d'une chaise derrière toi.",
    startingPosition: "Place-toi debout devant la chaise, dos tourné au siège, pieds à largeur des hanches.",
    instructions: [
      "Plie légèrement les genoux comme pour t'asseoir, sans aller jusqu'au contact avec l'assise.",
      "Reviens debout avec contrôle en poussant dans tes talons.",
    ],
    repetitions: 8,
    position: "standing",
    requiredEquipment: ["chair"],
    difficulty: 2,
    lowImpact: true,
    avoidWith: ["knees"],
    easierVariation: "Descends moins bas, ou touche légèrement l'assise.",
    harderVariation: "Marque une pause de 2 secondes en bas.",
    illustrationKey: "chair-half-squat",
    primaryBenefits: ["Force des jambes", "Stabilité"],
    cues: ["Genoux dans l'axe des pieds", "Garde le poids sur les talons", "Redresse le buste tout du long"],
    breathingCue: "Inspire en descendant, souffle en remontant.",
    bodyAreas: ["legs", "glutes"],
    repeatability: "normal",
  },
  {
    id: "seated-leg-extension",
    name: "Extension de jambe assise",
    category: "strength",
    description: "Renforce l'avant des cuisses en douceur, en position assise sécurisante.",
    startingPosition: "Assieds-toi bien droite au fond de la chaise, dos calé contre le dossier.",
    instructions: [
      "Tends une jambe à l'horizontale, genou verrouillé doucement.",
      "Redescends avec contrôle, sans reposer le pied brutalement.",
      "Répète, puis change de jambe.",
    ],
    repetitions: 10,
    position: "seated",
    requiredEquipment: ["chair"],
    difficulty: 1,
    lowImpact: true,
    easierVariation: "Réduis l'amplitude de l'extension.",
    harderVariation: "Tiens 2 secondes en haut du mouvement.",
    illustrationKey: "seated-leg-extension",
    primaryBenefits: ["Force des cuisses", "Stabilité des genoux"],
    cues: ["Garde le dos droit, calé contre le dossier", "Verrouille doucement le genou, sans forcer"],
    breathingCue: "Souffle en tendant la jambe.",
    bodyAreas: ["legs"],
    repeatability: "normal",
  },
  {
    id: "wall-pushup",
    name: "Pompes contre un mur",
    category: "strength",
    description: "Renforce les bras et la poitrine sans mettre les poignets ou le sol à contribution.",
    startingPosition: "Place les mains sur un mur, un peu plus larges que les épaules, à hauteur de poitrine.",
    instructions: [
      "Recule les pieds pour incliner le corps vers le mur.",
      "Plie les coudes pour rapprocher la poitrine du mur.",
      "Repousse le mur pour revenir à la position de départ.",
    ],
    repetitions: 8,
    position: "standing",
    requiredEquipment: [],
    difficulty: 1,
    lowImpact: true,
    avoidWith: ["shoulders"],
    easierVariation: "Rapproche-toi du mur pour réduire l'inclinaison.",
    harderVariation: "Éloigne davantage les pieds du mur.",
    illustrationKey: "wall-pushup",
    primaryBenefits: ["Force des bras", "Force de la poitrine"],
    cues: ["Garde le corps aligné, sans cambrer le dos", "Coudes orientés vers le bas, pas vers l'extérieur"],
    breathingCue: "Inspire en pliant les coudes, souffle en repoussant.",
    bodyAreas: ["chest", "arms", "shoulders"],
    repeatability: "normal",
  },
  {
    id: "supported-calf-raise",
    name: "Élévation des mollets avec appui",
    category: "strength",
    description: "Renforce les mollets et la stabilité des chevilles, appui sur une chaise.",
    startingPosition:
      "Place-toi debout derrière une chaise. Pose légèrement les mains sur le dossier et garde les pieds écartés de la largeur du bassin.",
    instructions: [
      "Monte lentement sur la pointe des pieds.",
      "Marque une courte pause en haut.",
      "Redescends doucement jusqu'à reposer complètement les talons.",
    ],
    repetitions: 10,
    position: "standing",
    requiredEquipment: ["chair"],
    difficulty: 1,
    lowImpact: true,
    avoidWith: ["ankles"],
    easierVariation: "Réduis l'amplitude et prends davantage appui sur la chaise.",
    harderVariation: "Marque une pause de 2 secondes en haut.",
    illustrationKey: "supported-calf-raise",
    primaryBenefits: ["Force des mollets", "Stabilité des chevilles"],
    cues: ["Garde le dos droit", "Regarde devant toi", "Utilise la chaise uniquement pour te stabiliser"],
    breathingCue: "Expire en montant. Inspire en redescendant.",
    bodyAreas: ["calves"],
    repeatability: "normal",
  },
  {
    id: "band-row",
    name: "Rowing avec élastique",
    category: "strength",
    description: "Renforce le haut du dos, utile pour une meilleure posture au quotidien.",
    startingPosition:
      "Assieds-toi droite, élastique fixé devant toi à hauteur de poitrine (ou tenu tendu, bras devant toi).",
    instructions: [
      "Tire les coudes vers l'arrière en rapprochant les omoplates.",
      "Marque une courte pause, coudes bien en arrière.",
      "Reviens lentement à la position de départ.",
    ],
    repetitions: 10,
    position: "seated",
    requiredEquipment: ["resistance_band"],
    difficulty: 2,
    lowImpact: true,
    easierVariation: "Utilise une tension plus légère sur l'élastique.",
    harderVariation: "Ralentis le retour sur 3 secondes.",
    illustrationKey: "band-row",
    primaryBenefits: ["Posture", "Force du dos"],
    cues: ["Garde les épaules basses, loin des oreilles", "Rapproche bien les omoplates l'une de l'autre"],
    breathingCue: "Souffle en tirant, inspire en revenant.",
    bodyAreas: ["back", "arms"],
    repeatability: "normal",
  },
  {
    id: "band-chest-opener",
    name: "Tirage élastique poitrine",
    category: "strength",
    description: "Ouvre la poitrine et renforce le haut du dos avec un élastique léger.",
    startingPosition: "Debout, tiens l'élastique à deux mains, bras tendus devant toi à hauteur de poitrine.",
    instructions: [
      "Écarte les bras sur les côtés en ouvrant la poitrine.",
      "Reviens avec contrôle à la position de départ.",
    ],
    repetitions: 10,
    position: "standing",
    requiredEquipment: ["resistance_band"],
    difficulty: 2,
    lowImpact: true,
    easierVariation: "Réduis l'amplitude d'ouverture.",
    illustrationKey: "band-chest-opener",
    primaryBenefits: ["Posture", "Mobilité des épaules"],
    cues: ["Garde les bras à hauteur de poitrine", "Ouvre à partir des omoplates, pas seulement des bras"],
    breathingCue: "Inspire en ouvrant les bras, souffle en revenant.",
    bodyAreas: ["chest", "shoulders", "back"],
    repeatability: "normal",
  },
  {
    id: "light-lateral-raise",
    name: "Élévations latérales légères",
    category: "strength",
    description: "Renforce doucement les épaules avec de petits poids ou à mains nues.",
    startingPosition: "Debout ou assise, bras le long du corps, un petit poids dans chaque main si tu en as.",
    instructions: [
      "Lève les bras sur les côtés jusqu'à hauteur d'épaule.",
      "Redescends avec contrôle.",
    ],
    repetitions: 8,
    position: "standing",
    requiredEquipment: ["light_dumbbells"],
    difficulty: 2,
    lowImpact: true,
    avoidWith: ["shoulders"],
    easierVariation: "Lève les bras moins haut, sans charge.",
    illustrationKey: "light-lateral-raise",
    primaryBenefits: ["Force des épaules"],
    cues: ["Coudes légèrement fléchis, pas totalement tendus", "Ne monte pas plus haut que les épaules"],
    breathingCue: "Souffle en levant les bras, inspire en redescendant.",
    bodyAreas: ["shoulders", "arms"],
    repeatability: "normal",
  },
  {
    id: "glute-bridge",
    name: "Pont fessier",
    category: "strength",
    description: "Renforce les fessiers et le bas du dos, allongée au sol ou sur le tapis.",
    startingPosition: "Allonge-toi sur le dos, genoux pliés, pieds à plat au sol, écartés de la largeur du bassin.",
    instructions: [
      "Pousse dans les talons pour lever le bassin vers le plafond.",
      "Marque une courte pause en haut.",
      "Redescends avec contrôle, sans laisser tomber le bassin.",
    ],
    repetitions: 8,
    position: "floor",
    requiredEquipment: ["mat"],
    difficulty: 2,
    lowImpact: true,
    avoidWith: ["back"],
    easierVariation: "Réduis la hauteur de montée du bassin.",
    harderVariation: "Marque une pause de 2 secondes en haut.",
    illustrationKey: "glute-bridge",
    primaryBenefits: ["Force des fessiers", "Stabilité du bassin"],
    cues: ["Serre les fessiers en haut du mouvement", "Évite de trop cambrer le bas du dos"],
    breathingCue: "Souffle en montant le bassin.",
    bodyAreas: ["glutes", "back", "core"],
    repeatability: "normal",
  },
  {
    id: "standing-hip-extension",
    name: "Extension de hanche debout avec appui",
    category: "strength",
    description: "Renforce les fessiers, appui sur une chaise pour l'équilibre.",
    startingPosition: "Debout, mains posées sur le dossier d'une chaise, pieds à largeur des hanches.",
    instructions: [
      "Tends une jambe vers l'arrière sans cambrer le dos.",
      "Marque une courte pause.",
      "Reviens avec contrôle, puis change de jambe.",
    ],
    repetitions: 8,
    position: "supported",
    requiredEquipment: ["chair"],
    difficulty: 1,
    lowImpact: true,
    easierVariation: "Réduis l'amplitude du mouvement.",
    illustrationKey: "standing-hip-extension",
    primaryBenefits: ["Force des fessiers", "Équilibre"],
    cues: ["Garde le bassin stable, face à la chaise", "Mouvement petit et contrôlé, pas besoin d'aller haut"],
    breathingCue: "Souffle en tendant la jambe vers l'arrière.",
    bodyAreas: ["glutes", "hips"],
    repeatability: "normal",
  },
  {
    id: "wall-core-activation",
    name: "Gainage debout contre un mur",
    category: "strength",
    description: "Active les muscles profonds du ventre en position debout, sans aller au sol.",
    startingPosition: "Dos appuyé contre un mur, pieds légèrement avancés, genoux légèrement fléchis.",
    instructions: [
      "Rentre doucement le nombril vers la colonne.",
      "Maintiens la position en respirant normalement.",
    ],
    durationSeconds: 20,
    position: "standing",
    requiredEquipment: [],
    difficulty: 1,
    lowImpact: true,
    avoidWith: ["back"],
    easierVariation: "Réduis la durée de maintien.",
    illustrationKey: "wall-core-activation",
    primaryBenefits: ["Sangle abdominale", "Posture"],
    cues: ["Garde le bas du dos proche du mur, sans forcer", "Épaules détendues, loin des oreilles"],
    breathingCue: "Respire normalement pendant le maintien.",
    bodyAreas: ["core"],
    repeatability: "normal",
  },
];
