import type { MoveExercise } from "../../shared/types";

export const strengthExercises: MoveExercise[] = [
  {
    id: "sit-to-stand",
    name: "Assis-debout",
    category: "strength",
    description:
      "L'exercice de base pour retrouver de la force dans les jambes, à partir d'une chaise.",
    instructions: [
      "Assieds-toi au bord de la chaise, pieds à largeur des hanches.",
      "Penche légèrement le buste vers l'avant.",
      "Pousse dans tes jambes pour te relever, puis rassieds-toi avec contrôle.",
    ],
    repetitions: 8,
    position: "seated",
    requiredEquipment: ["chair"],
    difficulty: 1,
    lowImpact: true,
    easierVariation: "Prends légèrement appui sur les mains ou les accoudoirs.",
    harderVariation: "Ralentis la descente sur 3 secondes.",
    illustrationKey: "sit-to-stand",
    primaryBenefits: ["Force des jambes", "Autonomie au quotidien"],
    cues: ["Regarde loin devant toi", "Talons bien ancrés au sol"],
    breathingCue: "Souffle en te levant, inspire en te rasseyant.",
    bodyAreas: ["legs", "glutes"],
    repeatability: "frequent",
  },
  {
    id: "chair-half-squat",
    name: "Demi-squat avec chaise",
    category: "strength",
    description: "Un mouvement de squat guidé par la présence rassurante d'une chaise derrière toi.",
    instructions: [
      "Place-toi debout devant la chaise, dos tourné au siège.",
      "Plie légèrement les genoux comme pour t'asseoir, sans aller jusqu'au contact.",
      "Reviens debout avec contrôle.",
    ],
    repetitions: 8,
    position: "standing",
    requiredEquipment: ["chair"],
    difficulty: 2,
    lowImpact: true,
    avoidWith: ["knees"],
    easierVariation: "Descends moins bas, ou touche légèrement l'assise.",
    harderVariation: "Marque une pause de 2 secondes en bas.",
    illustrationKey: "chair-half-squat",
    primaryBenefits: ["Force des jambes", "Stabilité"],
    cues: ["Genoux dans l'axe des pieds"],
    breathingCue: "Inspire en descendant, souffle en remontant.",
    bodyAreas: ["legs", "glutes"],
    repeatability: "normal",
  },
  {
    id: "seated-leg-extension",
    name: "Extension de jambe assise",
    category: "strength",
    description: "Renforce l'avant des cuisses en douceur, en position assise sécurisante.",
    instructions: [
      "Assieds-toi bien droite au fond de la chaise.",
      "Tends une jambe à l'horizontale, genou verrouillé doucement.",
      "Redescends avec contrôle, sans reposer le pied brutalement.",
    ],
    repetitions: 10,
    position: "seated",
    requiredEquipment: ["chair"],
    difficulty: 1,
    lowImpact: true,
    easierVariation: "Réduis l'amplitude de l'extension.",
    harderVariation: "Tiens 2 secondes en haut du mouvement.",
    illustrationKey: "seated-leg-extension",
    primaryBenefits: ["Force des cuisses", "Stabilité des genoux"],
    breathingCue: "Souffle en tendant la jambe.",
    bodyAreas: ["legs"],
    repeatability: "normal",
  },
  {
    id: "wall-pushup",
    name: "Pompes contre un mur",
    category: "strength",
    description: "Renforce les bras et la poitrine sans mettre les poignets ou le sol à contribution.",
    instructions: [
      "Place les mains sur un mur, un peu plus large que les épaules.",
      "Recule les pieds pour incliner le corps.",
      "Plie les coudes pour rapprocher la poitrine du mur, puis repousse.",
    ],
    repetitions: 8,
    position: "standing",
    requiredEquipment: [],
    difficulty: 1,
    lowImpact: true,
    avoidWith: ["shoulders"],
    easierVariation: "Rapproche-toi du mur pour réduire l'inclinaison.",
    harderVariation: "Éloigne davantage les pieds du mur.",
    illustrationKey: "wall-pushup",
    primaryBenefits: ["Force des bras", "Force de la poitrine"],
    breathingCue: "Inspire en pliant les coudes, souffle en repoussant.",
    bodyAreas: ["chest", "arms", "shoulders"],
    repeatability: "normal",
  },
  {
    id: "supported-calf-raise",
    name: "Élévation des mollets avec appui",
    category: "strength",
    description: "Renforce les mollets et la stabilité des chevilles, appui sur une chaise.",
    instructions: [
      "Debout, mains posées sur le dossier d'une chaise.",
      "Monte doucement sur la pointe des pieds.",
      "Redescends avec contrôle.",
    ],
    repetitions: 10,
    position: "standing",
    requiredEquipment: ["chair"],
    difficulty: 1,
    lowImpact: true,
    avoidWith: ["ankles"],
    easierVariation: "Réduis l'amplitude de la montée.",
    harderVariation: "Marque une pause de 2 secondes en haut.",
    illustrationKey: "supported-calf-raise",
    primaryBenefits: ["Force des mollets", "Stabilité des chevilles"],
    bodyAreas: ["calves"],
    repeatability: "normal",
  },
  {
    id: "band-row",
    name: "Rowing avec élastique",
    category: "strength",
    description: "Renforce le haut du dos, utile pour une meilleure posture au quotidien.",
    instructions: [
      "Fixe l'élastique devant toi à hauteur de poitrine, ou tiens-le tendu bras devant toi.",
      "Tire les coudes vers l'arrière en rapprochant les omoplates.",
      "Reviens lentement à la position de départ.",
    ],
    repetitions: 10,
    position: "seated",
    requiredEquipment: ["resistance_band"],
    difficulty: 2,
    lowImpact: true,
    easierVariation: "Utilise une tension plus légère sur l'élastique.",
    harderVariation: "Ralentis le retour sur 3 secondes.",
    illustrationKey: "band-row",
    primaryBenefits: ["Posture", "Force du dos"],
    breathingCue: "Souffle en tirant.",
    bodyAreas: ["back", "arms"],
    repeatability: "normal",
  },
  {
    id: "band-chest-opener",
    name: "Tirage élastique poitrine",
    category: "strength",
    description: "Ouvre la poitrine et renforce le haut du dos avec un élastique léger.",
    instructions: [
      "Tiens l'élastique à deux mains, bras tendus devant toi.",
      "Écarte les bras en ouvrant la poitrine.",
      "Reviens avec contrôle.",
    ],
    repetitions: 10,
    position: "standing",
    requiredEquipment: ["resistance_band"],
    difficulty: 2,
    lowImpact: true,
    easierVariation: "Réduis l'amplitude d'ouverture.",
    illustrationKey: "band-chest-opener",
    primaryBenefits: ["Posture", "Mobilité des épaules"],
    bodyAreas: ["chest", "shoulders", "back"],
    repeatability: "normal",
  },
  {
    id: "light-lateral-raise",
    name: "Élévations latérales légères",
    category: "strength",
    description: "Renforce doucement les épaules avec de petits poids ou à mains nues.",
    instructions: [
      "Debout ou assise, bras le long du corps.",
      "Lève les bras sur les côtés jusqu'à hauteur d'épaule.",
      "Redescends avec contrôle.",
    ],
    repetitions: 8,
    position: "standing",
    requiredEquipment: ["light_dumbbells"],
    difficulty: 2,
    lowImpact: true,
    avoidWith: ["shoulders"],
    easierVariation: "Lève les bras moins haut, sans charge.",
    illustrationKey: "light-lateral-raise",
    primaryBenefits: ["Force des épaules"],
    bodyAreas: ["shoulders", "arms"],
    repeatability: "normal",
  },
  {
    id: "glute-bridge",
    name: "Pont fessier",
    category: "strength",
    description: "Renforce les fessiers et le bas du dos, allongée au sol ou sur le tapis.",
    instructions: [
      "Allonge-toi sur le dos, genoux pliés, pieds au sol.",
      "Pousse dans les talons pour lever le bassin.",
      "Redescends avec contrôle, sans laisser tomber le bassin.",
    ],
    repetitions: 8,
    position: "floor",
    requiredEquipment: ["mat"],
    difficulty: 2,
    lowImpact: true,
    avoidWith: ["back"],
    easierVariation: "Réduis la hauteur de montée du bassin.",
    harderVariation: "Marque une pause de 2 secondes en haut.",
    illustrationKey: "glute-bridge",
    primaryBenefits: ["Force des fessiers", "Stabilité du bassin"],
    breathingCue: "Souffle en montant le bassin.",
    bodyAreas: ["glutes", "back", "core"],
    repeatability: "normal",
  },
  {
    id: "standing-hip-extension",
    name: "Extension de hanche debout avec appui",
    category: "strength",
    description: "Renforce les fessiers, appui sur une chaise pour l'équilibre.",
    instructions: [
      "Debout, mains sur le dossier d'une chaise.",
      "Tends une jambe vers l'arrière sans cambrer le dos.",
      "Reviens avec contrôle, puis change de jambe.",
    ],
    repetitions: 8,
    position: "supported",
    requiredEquipment: ["chair"],
    difficulty: 1,
    lowImpact: true,
    easierVariation: "Réduis l'amplitude du mouvement.",
    illustrationKey: "standing-hip-extension",
    primaryBenefits: ["Force des fessiers", "Équilibre"],
    bodyAreas: ["glutes", "hips"],
    repeatability: "normal",
  },
  {
    id: "wall-core-activation",
    name: "Gainage debout contre un mur",
    category: "strength",
    description: "Active les muscles profonds du ventre en position debout, sans aller au sol.",
    instructions: [
      "Dos appuyé contre un mur, pieds légèrement avancés.",
      "Rentre doucement le nombril vers la colonne.",
      "Maintiens la position en respirant normalement.",
    ],
    durationSeconds: 20,
    position: "standing",
    requiredEquipment: [],
    difficulty: 1,
    lowImpact: true,
    avoidWith: ["back"],
    easierVariation: "Réduis la durée de maintien.",
    illustrationKey: "wall-core-activation",
    primaryBenefits: ["Sangle abdominale", "Posture"],
    breathingCue: "Respire normalement pendant le maintien.",
    bodyAreas: ["core"],
    repeatability: "normal",
  },
];
